
import './globals.css'
import "remixicon/fonts/remixicon.css";


export const metadata = {
  title: 'biccas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
